Create main.js
possible issues:
Exception: The parameters (String,String,String) don't match the method signature for Utilities.formatDate.

need to convert dates to date objects in js?
in google sheet it is a date but not going into apps script as a date?