Update main.js
jk turns out that the
Exception: The parameters (String,String,String) don't match the method signature for Utilities.formatDate
actually was messing things up
for some reason the getData part was adding empty rows so I just added an "if first item in column empty do not add to object" (line 50)